### ISSUE TITLE
More explanation around `GH_BSN_REPO_AUTH_USER ` and `GH_BSN_REPO_AUTH_TOKEN`

### ISSUE THREAD

**Issue by oreporan** [ydemetriades/cfstep-github-buildstatus#2]
Can you please provide more information around what these 2 are

`GH_BSN_REPO_AUTH_USER` - why do I need this? why isn't a token enough?
`GH_BSN_REPO_AUTH_TOKEN` - Are these the "personal access tokens" that I generate? what scopes are required?

**Comment by oreporan** [comment]
Figured this out - closing

**Comment by oreporan** [comment]
Well actually I'm still not 100% sure what scopes are needed

**Comment by ydemetriades** [comment]
@oreporan I have reopened the issue to answer your question regarding the required scopes.
Let me do some investigation first!

**Comment by ydemetriades** [comment]
As stated [here](https://developer.github.com/v3/repos/statuses/#statuses) the required scope is `repo:status`. I will re-test to be sure that is the only one required.

I will close the issue and update the README file!
